import { defineMessages } from "react-intl";

export default defineMessages({
  title: "1.1 Cash",
  summary:
    "The most basic and intuitive form of money is cash – banknotes and coins.",
  text:
    '<p>The most basic and intuitive form of money is cash \u2013 banknotes and coins.</p>\r\n<p>The nature of cash has evolved over time. In the early days, it usually took the form of commodity money \u2013 an object made from something that had its own market value, such as coins made from gold. Later, commodity money was replaced by representative money, such as banknotes, that could be swapped for a certain fixed amount of gold or silver. Modern economies, including the euro area, are based on fiat money. This is money that is declared legal tender and issued by a central bank. Rather than relying on a substance or commodity, such as gold, to provide its underlying value, fiat money is widely accepted because people trust the central bank to keep the value of money stable over time.</p>\r\n<h4>1.1.1 Euro banknotes and coins</h4>\r\n<p>The legal tender of the euro area is the euro. More than 342 million people use it as the single currency in the 19 EU Member States comprising the euro area. This makes the euro a tangible symbol of European integration.</p>\r\n<p>Legally, euro banknotes are issued by the Eurosystem, which is made up of the European Central Bank (ECB) and the national central banks of the euro area countries. In practice, however, it is only the national central banks that actually issue euro banknotes and withdraw them from circulation. The ECB does not have a cash office. The legal issuers of euro coins are the national governments of euro area countries.</p>\r\n<p>After they have been issued, banknotes enter into circulation by being supplied over the counter by banks or via cash dispensers. Unless they are kept as a store of value, they are used for payments, returned to banks and recirculated until they become unfit (damaged or worn), at which point they are withdrawn from circulation by the national central banks.</p>\r\n<p>Further information about euro banknotes and coins is available in the euro section of the ECB\u2019s <a href="https://www.ecb.europa.eu/home/html/index.en.html">website</a>.</p>\r\n<h4>1.1.2 Banknote and coin statistics</h4>\r\n<p><a href="https://sdw.ecb.europa.eu/browse.do?node=9691111">Statistics about euro banknote and coin circulation</a> are produced on a monthly basis and can be found in the ECB\u2019s Statistical Data Warehouse.</p>\r\n<p>Low and medium-value notes (\u20ac5, \u20ac10, \u20ac20 and \u20ac50) are mostly used for day-to-day payments. Higher denominations (\u20ac100 and \u20ac200 \u2013 as well as \u20ac500 banknotes which are no longer issued but remain valid legal tender) are mainly used for expensive purchases and kept as a store of value.</p>\r\n<p>The total number of banknotes in circulation stood at [Value 1]\u00a0billion with an overall value of \u20ac[Value 2]\u00a0trillion\u00a0in [Date 1]. The number of euro coins in circulation totalled [Value 3] billion and their overall value was \u20ac[Value 4] billion.</p>',
  infographics1: "Number of banknotes and coins in circulation",
});
