import { defineMessages } from "react-intl";

export default defineMessages({
  title: "2.1 The Harmonised Index of Consumer Prices",
  summary: "What are the components of the HICP and how is it harmonised?",
  text:
    '<p class="MsoNormal">Inflation is typically measured using a consumer price index to compare the current prices of goods and services with their prices in earlier periods. In the euro area, the index used is the Harmonised Index of Consumer Prices (HICP). It is calculated by Eurostat, the statistical office of the European Union.</p>\r\n<p class="MsoNormal">The HICP is calculated on the basis of a \u201cshopping basket\u201d that contains goods and services that people typically spend their money on \u2013 goods such as food, clothes and cars, and services such as mobile phone charges, train tickets and rents for housing. Each of the euro area countries collects the prices of goods and services in the categories included in their respective national HICP baskets (up to 295 categories). Together they provide a good picture of price changes in the euro area economy as a whole.</p>\r\n<p>The HICP is \u201charmonised\u201d. This means that all the euro area countries have the same categories of goods and services in their baskets and use the same calculation methods. The composition of the HICP have been designed in such a way that the overall shopping basket remains representative in all countries, while reflecting differences in their consumption patterns across the euro area. The consumption of products such as olive oil and butter differs across countries: olive oil is purchased more frequently in the south of Europe whereas butter is more often purchased in the northern part of Europe. These differences are taken into account by giving each product a certain \u201cweight\u201d in the national shopping basket that reflects the product\u2019s share of households\u2019 spending in the country concerned.</p>\r\n<p>Have a look at the weights for the goods and services shown in the chart entitled \u201cConsumption shares across countries\u201d to see how they differ from one country to another. Do you think that your personal shopping basket differs from your country average? You can calculate your own inflation rate in Chapter 4. Why not give it a try?</p>\r\n<p><strong>2.1.1 Special consideration on the housing component of the HICP</strong></p>\r\n<p>Consumer price indices include rents for housing as this is a significant regular expenditure. They also include expenditures for heating, electricity, water, wastewater and even the cost of your rubbish collection service. There are still some issues related to expenditure on houses and flats owned by the people who live in them and the inclusion of these costs in the calculation of the HICP. As part of its monetary policy strategy review, the ECB is currently assessing what role these may play in measuring inflation.</p>',
  infographics1: "<p>Inflation rates across countries</p>",
  infographics2: "<p>Consumption shares across countries</p>",
});
