import { defineMessages } from "react-intl";

export default defineMessages({
  title: "2.2 How are prices collected?",
  summary:
    "How are prices collected for the HICP and does the basket change over time?",
  text:
    '<p><a name="_Hlk66952455"></a>Prices for the HICP are collected in different ways: manually in shops, in form of surveys, or electronically, via large supermarkets and \u201cdo-it-yourself\u201d shops (in the form of scanner data), or directly from websites.</p>\r\n<p>When prices are collected manually in shops, a single product is selected (for example a 500g packet of ground, caffeinated coffee, of the brand \u201cSunshine\u201d) and its shelf price in a certain supermarket, bakery shop or other outlet is recorded and tracked month by month. This method allows the prices of certain products to be collected as samples (for example, the price of ground, caffeinated coffee is collected, while prices of coffee beans or capsules may not be collected). Where scanner data are available from supermarkets, \u201cdo-it-yourself\u201d shops and/or pharmacies, a much greater amount of purchase data can be collected.</p>\r\n<p>The shopping baskets and product samples are not permanently fixed. Goods and services remain in the shopping basket as long as purchases of them are significant, and for at least one calendar year. In almost all cases they remain in the basket for longer than that. The quality of products in the basket can also change: a new model of a refrigerator may have better energy efficiency, or a new computer model may have a faster processor. Since inflation measurement supposes that products are identical over time (basket of the same products), quality improvements observed in reality are estimated and, subsequently, removed from the price index.</p>\r\n<p class="text-center"><img src="images/fridge-old.png" alt="" /> <img src="images/fridge-new.png" alt="" /></p>\r\n<p>Product samples and their weights in the basket are updated once a year to take into account the evolution of spending patterns and to include any new products or outlets. Over the longer term this means that developments in the HICP are not only the result of changes in the prices of the same goods and services, but also reflect changes in consumption and shopping patterns.</p>',
  infographics1: "<p>Statistics Insights: Inflation</p>",
});
